CREATE TABLE users (
  id integer primary key generated by default as identity,
  username text not null unique,
  f_name text not null,
  l_name text not null,
  password text not null,
  email text not null unique,
  city text not null,
  user_state text not null,
  zipcode numeric not null,
  date_registered timestamptz default now() NOT NULL
);