CREATE TABLE organizations (
  id integer primary key generated by default as identity,
  org_name text not null,
  org_phone text not null,
  org_st_addr text not null,
  org_city text not null,
  org_state text not null,
  org_zipcode text not null,
  pos_endorsements numeric,
  neg_endorsements numeric
);