CREATE TABLE comments (
  id integer primary key generated by default as identity,
  title text not null,
  content text not null,
  user_id text not null,
  org_id text not null,
  date_published timestamptz default now() not null
);